[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- App Libs
lib-log = { path = "../../libs/lib-log"}
lib-utils = { path = "../../libs/lib-utils" }

tracing = { workspace = true }
tokio = { version = "1.38.0", features = ["full"] }
